# Generated by Django 3.0.6 on 2020-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('height_in_m', models.IntegerField()),
                ('is_carnivore', models.BooleanField()),
            ],
        ),
    ]
